/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to one of `_getb67', `GETB67', `getb67' for Cray-2 and Cray-YMP
   systems. This function is required for `alloca.c' support on those systems.
   */
/* #undef CRAY_STACKSEG_END */

/* Define to 1 if using `alloca.c'. */
/* #undef C_ALLOCA */

/* Define to 1 if you have `alloca', as a function or macro. */
#define HAVE_ALLOCA 1

/* Define to 1 if you have <alloca.h> and it should be used (not on Ultrix).
   */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <argz.h> header file. */
#define HAVE_ARGZ_H 1

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* Linux Fast-STREAMS has this type. */
/* #undef HAVE_BCID_T */

/* Linux Fast-STREAMS has this type. */
/* #undef HAVE_BUFCALL_ID_T */

/* Define to 1 if you have the `bzero' function. */
#define HAVE_BZERO 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `fork' function. */
#define HAVE_FORK 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the `inet_ntoa' function. */
#define HAVE_INET_NTOA 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* The symbol ip_tos2prio is not exported by some kernels. Define this to the
   address of ip_tos2prio in the kernel system map so that kernel modules can
   be properly supported. */
/* #undef HAVE_IP_TOS2PRIO_ADDR */

/* The symbol ip_tos2prio is not exported by some kernels. Define this if the
   symbol ip_tos2prio is exported by your kernel so that kernel modules can be
   supported properly. */
/* #undef HAVE_IP_TOS2PRIO_EXPORT */

/* The symbol ip_tos2prio is not exported by some kernels. Define this if the
   symbol ip_tos2prio is either exported by your kernel, or can be stripped
   from the symbol map, so that kernel modules can be supported properly. */
/* #undef HAVE_IP_TOS2PRIO_SYMBOL */

/* Define to 1 if you have the <asm/softirq.h> header file. */
/* #undef HAVE_KINC_ASM_SOFTIRQ_H */

/* Define to 1 if you have the <linux/brlock.h> header file. */
/* #undef HAVE_KINC_LINUX_BRLOCK_H */

/* Define to 1 if you have the <linux/kdev_t.h> header file. */
#define HAVE_KINC_LINUX_KDEV_T_H 1

/* Define to 1 if you have the <linux/locks.h> header file. */
/* #undef HAVE_KINC_LINUX_LOCKS_H */

/* Define to 1 if you have the <linux/namei.h> header file. */
#define HAVE_KINC_LINUX_NAMEI_H 1

/* Define to 1 if you have the <linux/namespace.h> header file. */
#define HAVE_KINC_LINUX_NAMESPACE_H 1

/* Define to 1 if you have the <linux/security.h> header file. */
#define HAVE_KINC_LINUX_SECURITY_H 1

/* Define to 1 if you have the <linux/slab.h> header file. */
#define HAVE_KINC_LINUX_SLAB_H 1

/* Define to 1 if you have the <linux/snmp.h> header file. */
/* #undef HAVE_KINC_LINUX_SNMP_H */

/* Define to 1 if you have the <linux/statfs.h> header file. */
#define HAVE_KINC_LINUX_STATFS_H 1

/* Define to 1 if you have the <net/dst.h> header file. */
#define HAVE_KINC_NET_DST_H 1

/* Define to 1 if you have the <net/request_sock.h> header file. */
/* #undef HAVE_KINC_NET_REQUEST_SOCK_H */

/* Define to 1 if you have the <net/xfrm.h> header file. */
#define HAVE_KINC_NET_XFRM_H 1

/* Define to 1 if `protinfo.af_inet.ttl' is member of `struct sock'. */
/* #undef HAVE_KMEMB_STRUCT_SOCK_PROTINFO_AF_INET_TTL */

/* Define to 1 if `protinfo.af_inet.uc_ttl' is member of `struct sock'. */
/* #undef HAVE_KMEMB_STRUCT_SOCK_PROTINFO_AF_INET_UC_TTL */

/* Define to 1 if the system has the type 'irqreturn_t'. */
#define HAVE_KTYPE_IRQRETURN_T 1

/* Define to 1 if the system has the type 'pm_message_t'. */
/* #undef HAVE_KTYPE_PM_MESSAGE_T */

/* Define to 1 if you have the <langinfo.h> header file. */
#define HAVE_LANGINFO_H 1

/* Define to 1 if you have the `c' library (-lc). */
#define HAVE_LIBC 1

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* Define to 1 if you have the `LiS' library (-lLiS). */
#define HAVE_LIBLIS 1

/* Define to 1 if you have the `pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* Define to 1 if you have the `streams' library (-lstreams). */
/* #undef HAVE_LIBSTREAMS */

/* Define to 1 if you have the `xnet' library (-lxnet). */
/* #undef HAVE_LIBXNET */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if `lstat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_LSTAT_EMPTY_STRING_BUG */

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mempcpy' function. */
#define HAVE_MEMPCPY 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define to 1 if you have the `munmap' function. */
#define HAVE_MUNMAP 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the `nl_langinfo' function. */
#define HAVE_NL_LANGINFO 1

/* Define if your kernel supports the OpenSS7 Linux Kernel Sockets SCTP
   patches. This enables support in the INET driver for STREAMS on top of the
   OpenSS7 Linux Kernel Sockets SCTP implementation. */
/* #undef HAVE_OPENSS7_SCTP */

/* Define to 1 if the system has the type `ptrdiff_t'. */
#define HAVE_PTRDIFF_T 1

/* Define to 1 if your system has a GNU libc compatible `realloc' function,
   and to 0 otherwise. */
#define HAVE_REALLOC 1

/* Define to 1 if you have the `setlocale' function. */
#define HAVE_SETLOCALE 1

/* Define to 1 if you have the `socket' function. */
#define HAVE_SOCKET 1

/* Define to 1 if `stat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_STAT_EMPTY_STRING_BUG */

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio_ext.h> header file. */
#define HAVE_STDIO_EXT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `stpcpy' function. */
#define HAVE_STPCPY 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strcspn' function. */
#define HAVE_STRCSPN 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the `strtol' function. */
#define HAVE_STRTOL 1

/* Define to 1 if you have the `strtoul' function. */
#define HAVE_STRTOUL 1

/* Define to 1 if `st_blksize' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_BLKSIZE 1

/* Define to 1 if `st_blocks' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_BLOCKS 1

/* Define to 1 if `st_rdev' is member of `struct stat'. */
#define HAVE_STRUCT_STAT_ST_RDEV 1

/* Define to 1 if your `struct stat' has `st_blocks'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_BLOCKS' instead. */
#define HAVE_ST_BLOCKS 1

/* The symbol sysctl_rmem_default is not exported by some kernels. Define this
   to the address of sysctl_rmem_default in the kernel system map so that
   kernel modules can be properly supported. */
/* #undef HAVE_SYSCTL_RMEM_DEFAULT_ADDR */

/* The symbol sysctl_rmem_default is not exported by some kernels. Define this
   if the symbol sysctl_rmem_default is exported by your kernel so that kernel
   modules can be supported properly. */
/* #undef HAVE_SYSCTL_RMEM_DEFAULT_EXPORT */

/* The symbol sysctl_rmem_default is not exported by some kernels. Define this
   if the symbol sysctl_rmem_default is either exported by your kernel, or can
   be stripped from the symbol map, so that kernel modules can be supported
   properly. */
/* #undef HAVE_SYSCTL_RMEM_DEFAULT_SYMBOL */

/* The symbol sysctl_tcp_fin_timeout is not exported by some kernels. Define
   this to the address of sysctl_tcp_fin_timeout in the kernel system map so
   that kernel modules can be properly supported. */
/* #undef HAVE_SYSCTL_TCP_FIN_TIMEOUT_ADDR */

/* The symbol sysctl_tcp_fin_timeout is not exported by some kernels. Define
   this if the symbol sysctl_tcp_fin_timeout is exported by your kernel so
   that kernel modules can be supported properly. */
/* #undef HAVE_SYSCTL_TCP_FIN_TIMEOUT_EXPORT */

/* The symbol sysctl_tcp_fin_timeout is not exported by some kernels. Define
   this if the symbol sysctl_tcp_fin_timeout is either exported by your
   kernel, or can be stripped from the symbol map, so that kernel modules can
   be supported properly. */
/* #undef HAVE_SYSCTL_TCP_FIN_TIMEOUT_SYMBOL */

/* The symbol sysctl_wmem_default is not exported by some kernels. Define this
   to the address of sysctl_wmem_default in the kernel system map so that
   kernel modules can be properly supported. */
/* #undef HAVE_SYSCTL_WMEM_DEFAULT_ADDR */

/* The symbol sysctl_wmem_default is not exported by some kernels. Define this
   if the symbol sysctl_wmem_default is exported by your kernel so that kernel
   modules can be supported properly. */
/* #undef HAVE_SYSCTL_WMEM_DEFAULT_EXPORT */

/* The symbol sysctl_wmem_default is not exported by some kernels. Define this
   if the symbol sysctl_wmem_default is either exported by your kernel, or can
   be stripped from the symbol map, so that kernel modules can be supported
   properly. */
/* #undef HAVE_SYSCTL_WMEM_DEFAULT_SYMBOL */

/* Define when the STREAMS INET release supports module versions such as the
   OpenSS7 autoconf releases. */
/* #undef HAVE_SYS_INET_MODVERSIONS_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define when the LiS release provides its own module.h file such as 2.17
   GCOM LiS releases. */
#define HAVE_SYS_LIS_MODULE_H 1

/* Define when the LiS release supports module versions such as the OpenSS7
   autoconf release of LiS. */
/* #undef HAVE_SYS_LIS_MODVERSIONS_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define when the STREAMS SCTP release supports module versions such as the
   OpenSS7 autoconf releases. */
/* #undef HAVE_SYS_SCTP_MODVERSIONS_H */

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define when the STREAMS compatibiltiy release supports module versions such
   as the OpenSS7 autoconf releases. */
/* #undef HAVE_SYS_STRCOMP_MODVERSIONS_H */

/* Define when the Linux Fast-STREAMS release supports module versions such as
   the OpenSS7 autoconf releases. */
/* #undef HAVE_SYS_STREAMS_MODVERSIONS_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define when the STREAMS XNET release supports module versions such as the
   OpenSS7 autoconf releases. */
/* #undef HAVE_SYS_XNET_MODVERSIONS_H */

/* Define when the STREAMS XNS release supports module versions such as the
   OpenSS7 autoconf releases. */
/* #undef HAVE_SYS_XNS_MODVERSIONS_H */

/* The symbol tcp_cwnd_application_limited is not exported by some kernels.
   Define this to the address of tcp_cwnd_application_limited in the kernel
   system map so that kernel modules can be properly supported. */
/* #undef HAVE_TCP_CWND_APPLICATION_LIMITED_ADDR */

/* The symbol tcp_cwnd_application_limited is not exported by some kernels.
   Define this if the symbol tcp_cwnd_application_limited is exported by your
   kernel so that kernel modules can be supported properly. */
/* #undef HAVE_TCP_CWND_APPLICATION_LIMITED_EXPORT */

/* The symbol tcp_cwnd_application_limited is not exported by some kernels.
   Define this if the symbol tcp_cwnd_application_limited is either exported
   by your kernel, or can be stripped from the symbol map, so that kernel
   modules can be supported properly. */
/* #undef HAVE_TCP_CWND_APPLICATION_LIMITED_SYMBOL */

/* The symbol tcp_openreq_cachep is not exported by some kernels. Define this
   to the address of tcp_openreq_cachep in the kernel system map so that
   kernel modules can be properly supported. */
/* #undef HAVE_TCP_OPENREQ_CACHEP_ADDR */

/* The symbol tcp_openreq_cachep is not exported by some kernels. Define this
   if the symbol tcp_openreq_cachep is exported by your kernel so that kernel
   modules can be supported properly. */
/* #undef HAVE_TCP_OPENREQ_CACHEP_EXPORT */

/* The symbol tcp_openreq_cachep is not exported by some kernels. Define this
   if the symbol tcp_openreq_cachep is either exported by your kernel, or can
   be stripped from the symbol map, so that kernel modules can be supported
   properly. */
/* #undef HAVE_TCP_OPENREQ_CACHEP_SYMBOL */

/* The symbol tcp_set_keepalive is not exported by some kernels. Define this
   to the address of tcp_set_keepalive in the kernel system map so that kernel
   modules can be properly supported. */
/* #undef HAVE_TCP_SET_KEEPALIVE_ADDR */

/* The symbol tcp_set_keepalive is not exported by some kernels. Define this
   if the symbol tcp_set_keepalive is exported by your kernel so that kernel
   modules can be supported properly. */
/* #undef HAVE_TCP_SET_KEEPALIVE_EXPORT */

/* The symbol tcp_set_keepalive is not exported by some kernels. Define this
   if the symbol tcp_set_keepalive is either exported by your kernel, or can
   be stripped from the symbol map, so that kernel modules can be supported
   properly. */
/* #undef HAVE_TCP_SET_KEEPALIVE_SYMBOL */

/* The symbol tcp_sync_mss is not exported by some kernels. Define this to the
   address of tcp_sync_mss in the kernel system map so that kernel modules can
   be properly supported. */
/* #undef HAVE_TCP_SYNC_MSS_ADDR */

/* The symbol tcp_sync_mss is not exported by some kernels. Define this if the
   symbol tcp_sync_mss is exported by your kernel so that kernel modules can
   be supported properly. */
/* #undef HAVE_TCP_SYNC_MSS_EXPORT */

/* The symbol tcp_sync_mss is not exported by some kernels. Define this if the
   symbol tcp_sync_mss is either exported by your kernel, or can be stripped
   from the symbol map, so that kernel modules can be supported properly. */
/* #undef HAVE_TCP_SYNC_MSS_SYMBOL */

/* The symbol tcp_write_xmit is not exported by some kernels. Define this to
   the address of tcp_write_xmit in the kernel system map so that kernel
   modules can be properly supported. */
/* #undef HAVE_TCP_WRITE_XMIT_ADDR */

/* The symbol tcp_write_xmit is not exported by some kernels. Define this if
   the symbol tcp_write_xmit is exported by your kernel so that kernel modules
   can be supported properly. */
/* #undef HAVE_TCP_WRITE_XMIT_EXPORT */

/* The symbol tcp_write_xmit is not exported by some kernels. Define this if
   the symbol tcp_write_xmit is either exported by your kernel, or can be
   stripped from the symbol map, so that kernel modules can be supported
   properly. */
/* #undef HAVE_TCP_WRITE_XMIT_SYMBOL */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <values.h> header file. */
#define HAVE_VALUES_H 1

/* Define to 1 if you have the `vfork' function. */
#define HAVE_VFORK 1

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if `fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if `vfork' works. */
#define HAVE_WORKING_VFORK 1

/* Define to 1 if the system has the type `_Bool'. */
#define HAVE__BOOL 1

/* Define to 1 if you have the `__argz_count' function. */
#define HAVE___ARGZ_COUNT 1

/* Define to 1 if you have the `__argz_next' function. */
#define HAVE___ARGZ_NEXT 1

/* Define to 1 if you have the `__argz_stringify' function. */
#define HAVE___ARGZ_STRINGIFY 1

/* When defined, ISO is being compiled as a kernel linkable object. */
/* #undef ISO_CONFIG */

/* Define to perform internal structure tracking within ISO as well as to
   provide additional /proc filesystem files for examining internal
   structures. */
/* #undef ISO_CONFIG_DEBUG */

/* When defined, ISO is being compiled as a loadable kernel module. */
#define ISO_CONFIG_MODULE 

/* Define to perform no assertion checks but report software errors. This is
   the smallest footprint, highest performance mode of operation. */
/* #undef ISO_CONFIG_NONE */

/* Define to perform fundamental assertion checks. This is a safer mode of
   operation. */
#define ISO_CONFIG_SAFE 

/* Define to perform performance testing with debugging. This mode does not
   dump massive amounts of information into system logs, but peforms all
   assertion checks. */
/* #undef ISO_CONFIG_TEST */

/* Define for the linux 2.4 kernel series. */
/* #undef LINUX_2_4 */

/* Define for the linux 2.6 kernel series. */
#define LINUX_2_6 1

/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1

/* Define to 1 if `major', `minor', and `makedev' are declared in <mkdev.h>.
   */
/* #undef MAJOR_IN_MKDEV */

/* Define to 1 if `major', `minor', and `makedev' are declared in
   <sysmacros.h>. */
/* #undef MAJOR_IN_SYSMACROS */

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Name of package */
#define PACKAGE "striso"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bugs@openss7.org"

/* The package release date. */
#define PACKAGE_DATE "2006-10-01"

/* The Debian Epoch. This defaults to 0. */
#define PACKAGE_DEBEPOCH 0

/* The Debian Release. This defaults to 0. */
#define PACKAGE_DEBRELEASE "0"

/* The Package Epoch. This defaults to 1. */
#define PACKAGE_EPOCH 2

/* The Linux kernel version without EXTRAVERSION. */
#define PACKAGE_KNUMBER "2.6.5"

/* The Linux kernel version for which the package was configured. */
#define PACKAGE_KVERSION "2.6.5-7.282-smp"

/* Define to the full name of this package. */
#define PACKAGE_NAME "striso"

/* The Package Release. This defaults to Custom. */
#define PACKAGE_RELEASE "1.rc2"

/* The RPM Distribution. This defaults to automatic detection. */
#define PACKAGE_RPMDIST "SuSE Linux 9 (SUSE LINUX Enterprise Server 9 (i586))"

/* The RPM Epoch. This defaults to 0. */
#define PACKAGE_RPMEPOCH 0

/* The RPM Extra Release string. This defaults to automatic detection. */
#define PACKAGE_RPMEXTRA ".9"

/* The RPM Extra Release string. This defaults to automatic detection. */
#define PACKAGE_RPMEXTRA2 ".9"

/* The RPM Release. This defaults to 1. */
#define PACKAGE_RPMRELEASE "1"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "striso 0.9.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "striso"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.9.2"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to the type of arg 1 for `select'. */
#define SELECT_TYPE_ARG1 int

/* Define to the type of args 2, 3 and 4 for `select'. */
#define SELECT_TYPE_ARG234 (fd_set *)

/* Define to the type of arg 5 for `select'. */
#define SELECT_TYPE_ARG5 (struct timeval *)

/* Define to 1 if the `setpgrp' function takes no argument. */
#define SETPGRP_VOID 1

/* If using the C implementation of alloca, define if you know the
   direction of stack growth for your system; otherwise it will be
   automatically deduced at run-time.
	STACK_DIRECTION > 0 => grows toward higher addresses
	STACK_DIRECTION < 0 => grows toward lower addresses
	STACK_DIRECTION = 0 => direction of growth unknown */
/* #undef STACK_DIRECTION */

/* Define to 1 if the `S_IS*' macros in <sys/stat.h> do not work properly. */
/* #undef STAT_MACROS_BROKEN */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Version number of package */
#define VERSION "0.9.2"

/* Define for linux 2.5.48+ .ko kernel modules. */
#define WITH_KO_MODULES 1

/* Define for kernel symbol debugging. This has the effect of defeating
   inlines, making static declarations global, and activating all debugging
   macros. */
/* #undef _DEBUG */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

/* Define for maximum performance and minimum size. This has the effect of
   disabling all safety debugging macros. */
/* #undef _NONE */

/* Define for kernel image testing (profiling). This has the effect of -O0 -g,
   and setting assertions to TEST. */
/* #undef _OPTIMIZE_NONE */

/* Define for kernel image normal optimization. This has the effect of -O2 -g,
   and setting assertions to SAFE. */
#define _OPTIMIZE_NORMAL 1

/* Define for kernel image size optimizations. This has the effect of -Os and
   no -g, and disabling all assertions. */
/* #undef _OPTIMIZE_SIZE */

/* Define for kernel image speed optimizations. This has the effect of -O3 -g,
   and disabling all assertions. */
/* #undef _OPTIMIZE_SPEED */

/* Define for kernel safety. This has the effect of enabling safety debugging
   macros. This is the default. */
#define _SAFE 1

/* Define for kernel testing. This has the same effect as _DEBUG for now. */
/* #undef _TEST */

/* dnl Define for SuSv3. This is necessary for LiS and LfS and strsctp for
   that matter. */
#define _XOPEN_SOURCE 600

/* Define for RedHat BIGMEM kernel. */
/* #undef __BOOT_KERNEL_BIGMEM */

/* Define for RedHat BOOT kernel. */
/* #undef __BOOT_KERNEL_BOOT */

/* Define for RedHat DEBUG kernel. */
/* #undef __BOOT_KERNEL_DEBUG */

/* Define for RedHat/Mandrake ENTERPRISE kernel. */
/* #undef __BOOT_KERNEL_ENTERPRISE */

/* Define for RedHat HUGEMEM kernel. */
/* #undef __BOOT_KERNEL_HUGEMEM */

/* Define for RedHat/Mandrake kernel. */
#define __BOOT_KERNEL_H_ 

/* Define for Mandrake I586_UP_1GB kernel. */
/* #undef __BOOT_KERNEL_I586_UP_1GB */

/* Define for Mandrake I686_UP_4GB kernel. */
/* #undef __BOOT_KERNEL_I686_UP_4GB */

/* Define for Mandrake I686_UP_64GB kernel. */
/* #undef __BOOT_KERNEL_I686_UP_64GB */

/* Define for Mandrake MAXIMUM kernel. */
/* #undef __BOOT_KERNEL_MAXIMUM */

/* Define for Mandrake P3_SMP_64GB kernel. */
/* #undef __BOOT_KERNEL_P3_SMP_64GB */

/* Define for RedHat/Mandrake SECURE kernel. */
/* #undef __BOOT_KERNEL_SECURE */

/* Define for RedHat/Mandrake SMP kernel. */
#define __BOOT_KERNEL_SMP 1

/* Define for RedHat/Mandrake UP kernel. */
/* #undef __BOOT_KERNEL_UP */

/* Define for alpha RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_alpha */

/* Define for athlon RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_athlon */

/* Define for i386 RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_i386 */

/* Define for i586 RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_i586 */

/* Define for i686 RedHat/Mandrake kernel. */
#define __MODULE_KERNEL_i686 1

/* Define for ia32e RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_ia32e */

/* Define for ia64 RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_ia64 */

/* Define for ppc RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_ppc */

/* Define for ppc64 RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_ppc64 */

/* Define for s390 RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_s390 */

/* Define for s390x RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_s390x */

/* Define for sparc RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_sparc */

/* Define for sparc64 RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_sparc64 */

/* Define for x86_64 RedHat/Mandrake kernel. */
/* #undef __MODULE_KERNEL_x86_64 */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef mode_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to rpl_realloc if the replacement function should be used. */
/* #undef realloc */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */

/* Define as `fork' if `vfork' does not work. */
/* #undef vfork */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef volatile */
