/******************************************************************* vim: ft=c

 Copyright (c) 2001-2006  OpenSS7 Corporation <http://www.openss7.com>
 Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free Software
 Foundation; version 2 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 details.

 You should have received a copy of the GNU General Public License along with
 this program; if not, write to the Free Software Foundation, Inc., 675 Mass
 Ave, Cambridge, MA 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 *****************************************************************************/

#ifndef __SYS_LIS_CONFIG_H__
#define __SYS_LIS_CONFIG_H__

/*
 * GENERATED BY strconf-sh (Tue Jul 11 07:06:27 MDT 2006) FROM Config.master
 * EDITS TO THIS FILE WILL BE LOST: EDIT strconf-sh INSTEAD.
 */

/* -------------------------------------------------- */

#define CLONE__ID         1
#define CLONE__DRV_NAME   "clone-drvr"
#define CLONE__DRV        1
#define CLONE__DRV_ID     1
#define CLONE__CNTLS      0
#define CLONE__UNITS      1
#define CLONE__CMAJORS    1
#define CLONE__CMAJOR_0   230
#define CLONE__TYPE       -1

#define FIFO__ID         2
#define FIFO__DRV_NAME   "fifo"
#define FIFO__DRV        1
#define FIFO__DRV_ID     2
#define FIFO__CNTLS      0
#define FIFO__UNITS      512
#define FIFO__CMAJORS    1
#define FIFO__CMAJOR_0   231
#define FIFO__TYPE       -1

#define SLOOP__ID         3
#define SLOOP__DRV_NAME   "loop-around"
#define SLOOP__DRV        1
#define SLOOP__DRV_ID     3
#define SLOOP__CNTLS      0
#define SLOOP__UNITS      1
#define SLOOP__CMAJORS    1
#define SLOOP__CMAJOR_0   232
#define SLOOP__TYPE       -1

#define MMUX__ID         4
#define MMUX__DRV_NAME   "mini-mux"
#define MMUX__DRV        1
#define MMUX__DRV_ID     4
#define MMUX__CNTLS      0
#define MMUX__UNITS      1
#define MMUX__CMAJORS    1
#define MMUX__CMAJOR_0   233
#define MMUX__TYPE       -1

#define PRINTK__ID         5
#define PRINTK__DRV_NAME   "printk"
#define PRINTK__DRV        1
#define PRINTK__DRV_ID     5
#define PRINTK__CNTLS      0
#define PRINTK__UNITS      1
#define PRINTK__CMAJORS    1
#define PRINTK__CMAJOR_0   234
#define PRINTK__TYPE       -1

#define SAD__ID         6
#define SAD__DRV_NAME   "sad"
#define SAD__DRV        1
#define SAD__DRV_ID     6
#define SAD__CNTLS      0
#define SAD__UNITS      1
#define SAD__CMAJORS    1
#define SAD__CMAJOR_0   235
#define SAD__TYPE       -1

#define MTDRV__ID         7
#define MTDRV__DRV_NAME   "mtdrv"
#define MTDRV__DRV        1
#define MTDRV__DRV_ID     7
#define MTDRV__CNTLS      0
#define MTDRV__UNITS      1
#define MTDRV__CMAJORS    1
#define MTDRV__CMAJOR_0   236
#define MTDRV__TYPE       -1

#define NULS__ID         8
#define NULS__DRV_NAME   "nuls"
#define NULS__DRV        1
#define NULS__DRV_ID     8
#define NULS__CNTLS      0
#define NULS__UNITS      1
#define NULS__CMAJORS    1
#define NULS__CMAJOR_0   237
#define NULS__TYPE       -1

#define ECHO__ID         9
#define ECHO__DRV_NAME   "echo"
#define ECHO__DRV        1
#define ECHO__DRV_ID     9
#define ECHO__CNTLS      0
#define ECHO__UNITS      1
#define ECHO__CMAJORS    1
#define ECHO__CMAJOR_0   238
#define ECHO__TYPE       -1

#define MUX__ID         10
#define MUX__DRV_NAME   "mux"
#define MUX__DRV        1
#define MUX__DRV_ID     10
#define MUX__CNTLS      0
#define MUX__UNITS      1
#define MUX__CMAJORS    1
#define MUX__CMAJOR_0   239
#define MUX__TYPE       -1

#define PIPEMOD__ID         11
#define PIPEMOD__MOD_NAME   "pipemod"
#define PIPEMOD__MOD        1
#define PIPEMOD__MOD_ID     11
#define PIPEMOD__UNITS      0
#define PIPEMOD__TYPE       -1

#define CONNLD__ID         12
#define CONNLD__MOD_NAME   "connld"
#define CONNLD__MOD        1
#define CONNLD__MOD_ID     12
#define CONNLD__UNITS      0
#define CONNLD__TYPE       -1

#define RELAY__ID         13
#define RELAY__MOD_NAME   "relay"
#define RELAY__MOD        1
#define RELAY__MOD_ID     13
#define RELAY__UNITS      0
#define RELAY__TYPE       -1

#define RELAY2__ID         14
#define RELAY2__MOD_NAME   "relay2"
#define RELAY2__MOD        1
#define RELAY2__MOD_ID     14
#define RELAY2__UNITS      0
#define RELAY2__TYPE       -1

#define BUFMOD__ID         15
#define BUFMOD__MOD_NAME   "bufmod"
#define BUFMOD__MOD        1
#define BUFMOD__MOD_ID     15
#define BUFMOD__UNITS      0
#define BUFMOD__TYPE       -1

#define TESTMOD__ID         16
#define TESTMOD__MOD_NAME   "testmod"
#define TESTMOD__MOD        1
#define TESTMOD__MOD_ID     16
#define TESTMOD__UNITS      0
#define TESTMOD__TYPE       -1

#define NULLMOD__ID         17
#define NULLMOD__MOD_NAME   "nullmod"
#define NULLMOD__MOD        1
#define NULLMOD__MOD_ID     17
#define NULLMOD__UNITS      0
#define NULLMOD__TYPE       -1

/* -------------------------------------------------- */

#endif  /* __SYS_LIS_CONFIG_H__ */

/*
 * vim: ft=c
 */
